### ISSUE TITLE
reason:"Document update conflict." statusCode:409

### ISSUE THREAD

**Issue by djinete** [adriantanasa/connect-cloudant-store#5]
Hi Adrian, when we use the store , this way 
  var store = new CloudantStore(
        {
            database: dbconfig.dbCredentials.sessionName,
            dbRemoveExpMax: 100,
            disableTTLRefresh: true,
            url: dbconfig.dbCredentials.url,
        }
    );
Obtain the follow error reason:"Document update conflict." statusCode:409, 
Seems like the option   disableTTLRefresh: true, its not working , Any ideas? I really need your help
Thank's a lot.

**Comment by tortilaman** [comment]
Also encountering this issue.

**Comment by adriantanasa** [comment]
@djinete I don't think you have an option to completely remove the document conflicts while using the session store with Cloudant, especially if you have multiple instances running for same application. disableTTLRefresh will reduce the amount of conflicts, but is not removing them completely.
